name: "HAIAMM Practice Implementation"
description: "Track implementation of a HAIAMM security practice"
title: "[PRACTICE] "
labels: ["haiamm", "implementation"]
body:
  - type: markdown
    attributes:
      value: |
        ## HAIAMM Practice Implementation Tracker
        Use this template to track the implementation of a specific HAIAMM practice within your AI security program.

  - type: dropdown
    id: function
    attributes:
      label: Business Function
      description: Which HAIAMM function does this practice belong to?
      options:
        - "Governance - How you govern AI security"
        - "Building - How you build AI agents securely"
        - "Verification - How you verify AI agents work correctly"
        - "Operations - How you run AI agents safely"
    validations:
      required: true

  - type: dropdown
    id: practice
    attributes:
      label: Practice
      description: Which practice are you implementing?
      options:
        - "SM - Strategy & Metrics"
        - "PC - Policy & Compliance"
        - "EG - Education & Guidance"
        - "TA - Threat Assessment"
        - "SR - Security Requirements"
        - "SA - Secure Architecture"
        - "DR - Design Review"
        - "IR - Implementation Review"
        - "ST - Security Testing"
        - "IM - Issue Management"
        - "EH - Environment Hardening"
        - "ML - Monitoring & Logging"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Primary Domain
      description: Which domain is the primary focus?
      options:
        - "Software - AI model code, applications, integrations"
        - "Infrastructure - Compute, storage, networks"
        - "Endpoints - APIs, UIs, integration points"
        - "Data - Training data, model I/O, pipelines"
        - "Processes - Governance, compliance, operations"
        - "Vendors - Third-party AI services and tools"
    validations:
      required: true

  - type: dropdown
    id: current_level
    attributes:
      label: Current Maturity Level
      description: What is your current maturity level for this practice?
      options:
        - "Level 0 - Not started"
        - "Level 1 - Foundation (ad-hoc, individual effort)"
        - "Level 2 - Structured (documented, consistent)"
        - "Level 3 - Optimized (measured, continuous improvement)"
    validations:
      required: true

  - type: dropdown
    id: target_level
    attributes:
      label: Target Maturity Level
      description: What maturity level are you targeting?
      options:
        - "Level 1 - Foundation"
        - "Level 2 - Structured"
        - "Level 3 - Optimized"
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Implementation Objective
      description: What are you trying to achieve with this implementation?
      placeholder: |
        Example: Establish baseline threat assessment capability for our AI agent deployment, focusing on prompt injection and tool misuse risks.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Which AI systems, teams, or processes are in scope?
      placeholder: |
        - AI Systems: Customer support chatbot, internal code assistant
        - Teams: ML Engineering, Platform Security
        - Processes: Model deployment pipeline
    validations:
      required: true

  - type: textarea
    id: activities
    attributes:
      label: Planned Activities
      description: What specific activities will you complete?
      placeholder: |
        - [ ] Activity 1: Description
        - [ ] Activity 2: Description
        - [ ] Activity 3: Description
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How will you measure successful implementation?
      placeholder: |
        - Metric 1: 100% of AI systems have documented threat models
        - Metric 2: Threat assessment completed before each deployment
        - Metric 3: <30 day mean time from threat identification to mitigation
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What dependencies or prerequisites exist?
      placeholder: |
        - Requires: AI system inventory (from SM practice)
        - Blocked by: None
        - Enables: SR (Security Requirements) practice
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Implementation Risks
      description: What risks might impact this implementation?
      placeholder: |
        - Resource constraints: Only 1 FTE allocated
        - Technical debt: Legacy systems lack API instrumentation
        - Organizational: Cross-team coordination required
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Implementation priority
      options:
        - "Critical - Blocking production or addressing active risk"
        - "High - Required for compliance or major risk reduction"
        - "Medium - Important for security posture improvement"
        - "Low - Nice to have, long-term improvement"
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources Required
      description: What resources are needed?
      placeholder: |
        - People: 0.5 FTE security engineer, 0.25 FTE ML engineer
        - Tools: Threat modeling tool, documentation platform
        - Budget: $X for tooling
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant HAIAMM documentation or resources
      placeholder: |
        - HAIAMM Practice Guide: [link]
        - Related OWASP Risk: ASI01, LLM01
        - Internal documentation: [link]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## Verifhai Integration (Optional)
        Complete this section if this issue was generated from a Verifhai assessment.

  - type: dropdown
    id: verifhai_generated
    attributes:
      label: Generated by Verifhai?
      description: Was this issue created from a Verifhai skill session?
      options:
        - "No - Manually created"
        - "Yes - /verifhai-assess"
        - "Yes - /verifhai-practice"
        - "Yes - /verifhai-measure"
        - "Yes - /verifhai-start"
    validations:
      required: false

  - type: input
    id: verifhai_session
    attributes:
      label: Verifhai Session Reference
      description: Session date or ID for traceability
      placeholder: "2026-01-07 or leave blank"
    validations:
      required: false
